version: "3.8"

services:
  odc-postgres:
    image: kartoza/postgis:11.0-2.5
    container_name: odc-postgres
    environment:
      - POSTGRES_DB=opendatacube
      - POSTGRES_PASSWORD=opendatacubepassword
      - POSTGRES_USER=opendatacube
    ports:
      - "5439:5432"
    restart: always
    healthcheck:
      test: pg_isready -h 127.0.0.1 -U opendatacube -d opendatacube

  sandbox:
    environment:
      - DATACUBE_DB_URL=postgresql://opendatacube:opendatacubepassword@host.docker.internal:5439/opendatacube

  dt-postgres:
    image: postgis/postgis
    container_name: dt-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: always
    healthcheck:
      test: pg_isready -h 127.0.0.1 -U $POSTGRES_USER -d $POSTGRES_DB
  
