version: '3.8'

volumes:
  postgres_db_vol:

services:
  db_postgres:
    image: postgis/postgis
    container_name: db_postgres_digital_twin
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_db_vol:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: pg_isready -h 127.0.0.1 -U $POSTGRES_USER -d $POSTGRES_DB

  backend:
    build: .
    container_name: backend_digital_twin
    network_mode: host
    env_file: .env
    depends_on:
      db_postgres:
        condition: service_healthy
